 
package quizapplication;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author RAMSON
 */
public class QuizApp extends javax.swing.JFrame {

    String[] questions={"1+1= ?","3 -3 = ?","5 + 5= ?","10 X 9= ?","100 - 50= ?"};
    // the correct answer is the last option
    //we will check for the last option for correctness of the answers
    String[][] options={{"10","3","2","11","2"},{"14","13","9","0","0"},{"20","10","34","45","10"},{"90","32","65","18","90"},{"100","50","60","54","50"}};
    int index=0,correct=0;
    ButtonGroup bg=new ButtonGroup();
    
    
    public QuizApp() {
        initComponents();
        bg.add(jRadio1);
        bg.add(jRadio2);
        bg.add(jRadio3);
        bg.add(jRadio4);
        next_quizActionPerformed(null);
    }

    
    public void getselectedOption(JRadioButton rbttn){
        //get the selected value from the radiobutton
        //increment the index
        //disable the radioButtons
        //check if the user selected the right answers
        System.out.println(rbttn.getText());
        System.out.println(options[index][4]);
        if(rbttn.getText().equals(options[index][4])){
            correct++;
        }
        index++;
        enableRButtons(false);
        
    }
    //enable/disable radioButtons
    public void enableRButtons(boolean yes_or_no){
        jRadio1.setEnabled(yes_or_no);
        jRadio2.setEnabled(yes_or_no);
        jRadio3.setEnabled(yes_or_no);
        jRadio4.setEnabled(yes_or_no);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        quiz_container = new javax.swing.JLabel();
        jRadio2 = new javax.swing.JRadioButton();
        jRadio1 = new javax.swing.JRadioButton();
        jRadio4 = new javax.swing.JRadioButton();
        jRadio3 = new javax.swing.JRadioButton();
        next_quiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        panel2.setBackground(new java.awt.Color(204, 204, 204));

        quiz_container.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quiz_container.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quiz_container.setText("Question here ???");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quiz_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quiz_container, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        jRadio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadio2.setText("jRadioButton2");
        jRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio2ActionPerformed(evt);
            }
        });

        jRadio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadio1.setText("jRadioButton1");
        jRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1ActionPerformed(evt);
            }
        });

        jRadio4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadio4.setText("jRadioButton4");
        jRadio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio4ActionPerformed(evt);
            }
        });

        jRadio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadio3.setText("jRadioButton3");
        jRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio3ActionPerformed(evt);
            }
        });

        next_quiz.setBackground(new java.awt.Color(255, 51, 51));
        next_quiz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next_quiz.setForeground(new java.awt.Color(255, 255, 255));
        next_quiz.setText("Next");
        next_quiz.setBorder(null);
        next_quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_quizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadio4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(next_quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jRadio1)
                .addGap(29, 29, 29)
                .addComponent(jRadio2)
                .addGap(32, 32, 32)
                .addComponent(jRadio3)
                .addGap(28, 28, 28)
                .addComponent(jRadio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(next_quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1ActionPerformed
        // increment to go to next question
          getselectedOption(jRadio1);
    }//GEN-LAST:event_jRadio1ActionPerformed

    private void jRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio2ActionPerformed
        // TODO add your handling code here:
         getselectedOption(jRadio2);
    }//GEN-LAST:event_jRadio2ActionPerformed

    private void jRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio3ActionPerformed
        // TODO add your handling code here:
         getselectedOption(jRadio3);
    }//GEN-LAST:event_jRadio3ActionPerformed

    private void jRadio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio4ActionPerformed
        // TODO add your handling code here:
        getselectedOption(jRadio4);
    }//GEN-LAST:event_jRadio4ActionPerformed

    private void next_quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_quizActionPerformed
      
        if(next_quiz.getText().equals("Restart The Quiz")){
            //restart the quiz
            next_quiz.setText("Next");
             panel2.setBackground(new java.awt.Color(204, 204, 204));
            index=0;
            correct=0;
        }
        
        if(index ==questions.length){
         //display the user score
          quiz_container.setText("Your Score : "+ correct +" / "+questions.length);
          
          if(correct >=(float) questions.length/2){
              panel2.setBackground(Color.green);
          }
          else{
              panel2.setBackground(Color.red);
          }
          next_quiz.setText("Restart The Quiz");
       }
       else{
        //enable the radioButtons
          enableRButtons(true);
       //display the next question
         quiz_container.setText(questions[index]);
         jRadio1.setText(options[index][0]);
         jRadio2.setText(options[index][1]);
         jRadio3.setText(options[index][2]);
         jRadio4.setText(options[index][3]);
           if(index==questions.length-1){
          next_quiz.setText("Finish and see the Results");
           }
       }
        //clear the selection
         bg.clearSelection();
    }//GEN-LAST:event_next_quizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadio1;
    private javax.swing.JRadioButton jRadio2;
    private javax.swing.JRadioButton jRadio3;
    private javax.swing.JRadioButton jRadio4;
    private javax.swing.JButton next_quiz;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel quiz_container;
    // End of variables declaration//GEN-END:variables
}
